services:
  rproxy:
    container_name: rproxy
    image: "rproxy:latest"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    build:
      context: ../rproxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - root-page
      - cv
      - miam
      - checklist
      - api-server
    deploy:
      restart_policy:
        condition: any
  root-page:
    container_name: root-page
    image: "root-page:latest"
    build:
      context: ../root-page
    deploy:
      restart_policy:
        condition: any
  cv:
    container_name: cv
    image: "cv:latest"
    build:
      context: ../cv
    deploy:
      restart_policy:
        condition: any
  miam:
    container_name: miam
    image: "miam:latest"
    build:
      context: ../ #Must be the root of the project to get shared/common files
      dockerfile: ./miam/Dockerfile
    deploy:
      restart_policy:
        condition: any
  checklist:
    container_name: checklist
    image: "checklist:latest"
    build:
      context: ../ #Must be the root of the project to get shared/common files
      dockerfile: ./checklist/Dockerfile
    deploy:
      restart_policy:
        condition: any
  api-server:
    container_name: api-server
    image: "api-server:latest"
    environment:
      - PORT=3000
    build:
      context: ../ #Must be the root of the project to get shared/common files
      dockerfile: ./api-server/Dockerfile
    volumes:
      - /data/sqllitedb:/data/sqllitedb
    deploy:
      restart_policy:
        condition: any
